// Generated by https://quicktype.io

export interface dataTravel {
  animalExperiences: AnimalExperiences;
  familyTravel: AnimalExperiences;
  cruises: AnimalExperiences;
  gearAndSport: AnimalExperiences;
  transport: AnimalExperiences;
}

export interface AnimalExperiences {
  header: Header;
  items: Item[];
}

export interface Header {
  label: string;
  title: string;
  description: string;
  ctaText: string;
  ctaLink: string;
}

export interface Item {
  id: number;
  title: string;
  image: string;
  description: string;
  location?: string;
  link: string;
  duration?: string;
  category?: string;
  type?: string;
}
